service: typer-app-mfe

useDotenv: true

frameworkVersion: "3"

plugins:
  - serverless-s3-cleaner

custom:
  serverless-s3-cleaner:
    buckets:
      - typer-app-mfe-${env:STAGE}

provider:
  name: aws
  stage: development
  region: ${env:REGION}
  runtime: nodejs14.x
  iam:
    role:
      name: typer-app-mfe-${env:STAGE}-role
      statements:
        - Effect: "Allow"
          Action:
            - "s3:Put*"
            - "s3:Get*"
            - "s3:List*"
            - "s3:Delete*"
            - "s3:GetBucketPolicy"
            - "s3:PutBucketPolicy"
          Resource:
            - arn:aws:s3:::typer-app-mfe-${env:STAGE}/*
            - arn:aws:s3:::typer-app-mfe-${env:STAGE}

resources:
  Resources:
    TyperAppMfeBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: typer-app-mfe-${env:STAGE}
        WebsiteConfiguration:
          IndexDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"
    TyperAppMfeBucketPolicy:
      Type: AWS::S3::BucketPolicy
      DependsOn: TyperAppMfeBucket
      Properties:
        Bucket: typer-app-mfe-${env:STAGE}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: "arn:aws:s3:::typer-app-mfe-${env:STAGE}/*"
