service: typer-app-mfe

useDotenv: true

frameworkVersion: "3"

plugins:
  - serverless-s3-cleaner

custom:
  serverless-s3-cleaner:
    buckets:
      - typer-app-mfe-${opt:stage,self:provider.stage}

provider:
  name: aws
  stage: dev
  region: "us-east-1"
  runtime: nodejs14.x
  environment:
    REGION: us-east-1
    BUCKET_NAME: typer-app-mfe-${opt:stage,self:provider.stage}
    NODE_ENV: ${opt:stage,self:provider.stage}
  iam:
    role:
      name: typer-app-mfe-${opt:stage,self:provider.stage}-role
      statements:
        - Effect: "Allow"
          Action:
            - "s3:Put*"
            - "s3:Get*"
            - "s3:List*"
            - "s3:Delete*"
            - "s3:GetBucketPolicy"
            - "s3:PutBucketPolicy"
          Resource:
            - arn:aws:s3:::typer-app-mfe-${opt:stage,self:provider.stage}/*
            - arn:aws:s3:::typer-app-mfe-${opt:stage,self:provider.stage}

resources:
  Resources:
    TyperAppMfeBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: typer-app-mfe-${opt:stage,self:provider.stage}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"
    TyperAppMfeBucketPolicy:
      Type: AWS::S3::BucketPolicy
      DependsOn: TyperAppMfeBucket
      Properties:
        Bucket: typer-app-mfe-${opt:stage,self:provider.stage}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: "arn:aws:s3:::typer-app-mfe-${opt:stage,self:provider.stage}/*"
