name: Deploy to prod stage

on:
  push:
    branches:
      - main
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REGION: ${{ vars.REGION }}
  STAGE: prod
  IMPORTMAP_DEPLOYER_API_HOST: ${{ vars.IMPORTMAP_DEPLOYER_API_HOST }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: "Install Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: "Install dependencies"
        run: yarn install --frozen-lockfile
      - name: "Build"
        run: yarn build
      - name: "Create .env file"
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> .env
          echo "REGION=${REGION}" > .env
          echo "STAGE=${STAGE}" >> .env
          echo "IMPORTMAP_DEPLOYER_API_HOST=${IMPORTMAP_DEPLOYER_API_HOST}" >> .env
      - name: "Run serverless deploy"
        run: yarn sls:deploy:prod
      - name: "Deploy"
        run: yarn deploy
